export { default as cats } from "./cats.png";
export { default as logo } from "./q_logo.png";
export { default as baby_chick } from "./Baby Chick.png";
export { default as dolphin } from "./dolphin.png";
export { default as egg } from "./egg.png";
export { default as flag } from "./flag.png";
export { default as front_chick } from "./Front-Facing Baby Chick.png";
export { default as hatching_chick } from "./Hatching Chick.png";
export { default as auto_mobile } from "./Automobile.png";
export { default as q_docs2 } from "./q_docs_2.png";
export { default as example_1 } from "./Example1.png";
export { default as example_2 } from "./Example2.png";
export { default as example_3 } from "./Example3.png";
export { default as example_4 } from "./Example4.png";
export { default as example_5 } from "./Example5.png";
export { default as example_6 } from "./Example6.png";
export { default as example_7 } from "./Example7.png";
export { default as example_8 } from "./Example8.png";
export { default as example_9 } from "./Example9.png";
