import AboutPage from "./AboutPage";
import ExamplePage from "./ExamplePage";
import LicensePage from "./LicensePage";
import ContributingPage from "./ContributingPage";
export { default as ListPage } from "./ListPage";
export { default as ManagePage } from "./ManagePage";
export { default as ResourcePage } from "./ResourcePage";
export { default as RegistPage } from "./RegistPage";
export { default as WaitingPage } from "./WaitingPage";
export { default as AboutPage } from "./AboutPage";
export { default as DocsPage } from "./DocsPage";
export { default as ExamplePage } from "./ExamplePage";
export { default as LicensePage } from "./LicensePage";
export { default as ContributingPage } from "./ContributingPage";
